package CodSoft;
import java.util.*;
public class Task1_NumberGame {

	public static void main(String[] args) 
	{
		Scanner in = new Scanner(System.in);
		System.out.println("Let's Play the Number Game ");
		System.out.println();
		int points=0,score=0,r=1;
		for(;;)
		{
			System.out.println("ROUND "+r);
			System.out.println();
			int compguess=(int)((Math.random()*100)+1);
			System.out.println("Computer has generated a number from 1 - 100");
			System.out.println("You have 5 attempts to guess the number. ");
			System.out.println("BEST OF LUCK.... ");
			for(int i=5;i>=1;i--)
			{
				System.out.println("Enter your Guess: ");
				int userguess=in.nextInt();
				if(userguess==compguess)
				{
					System.out.println("Correct guess. CONGRATULATIONS!! ");
					points++;
					score++;
					break;
				}
				else if (userguess>compguess)
				{
					System.out.println("Your guess is too high. Try again!");
				}
				else
				{
					System.out.println("Your guess is too low. Try again!");
				}
				System.out.println("Attempts left: "+(i-1));
				if(i==1)
				{
					System.out.println("Sorry, no attempts left");
					System.out.println("The number generated by the computer was : "+compguess);
				}
				
			}
			System.out.println("\nScore for round "+ r+":- "+score);
			score=0;
			System.out.println("Do you want to play round "+(r+1)+" ? (Yes/No):- ");
			String s=in.next();
			if(s.equalsIgnoreCase("Yes"))
			r++;
			else if(s.equalsIgnoreCase("No"))
			break;
			System.out.println();
		}
		System.out.println("Total number of rounds you played: "+r);
		System.out.print("Final Score of all the rounds: "+points);
	}
}
